name: blast
channels:
  - conda-forge
  - bioconda
channel_priority: strict
dependencies:
  - python=3.11
  - pandas
  - streamlit
  - biopython
  - lxml
  - requests
  - plotnine
  - pyarrow
